[package]
name = "verge-ipc"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0"
publish = false

[dependencies]
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
verge-domain = { path = "../verge-domain" }
verge-ui = { path = "../verge-ui" }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
